export const SCREEN_NAME = {
  PROFILE_SCREEN: "ProfileScreen",
  TEST_SCREEN: "Test",
  HOME_NAVIGATOR: "HomeNavigator",
  TEST_ANIMATED: "TestAnimated",
  CATEGORYMENU_SCREEN: "CategoryMenuScreen",
  CART_SCREEN: "CartScreen",
  CHANGEPASSWORD_SCREEN: "ChangePasswordScreen",
  NOTIFICATIONS_NAVIGATOR: "Notifications",
  ADDRESSBOOK_SCREEN: "AddressBookScreen",
  STORECATEGORY_SCREEN: "StoreCategoryScreen",
  STORECATEGORYNAVIGATOR: "StoreCategoryNavigator",
  LOGINSCREEN: "LoginScreen",
  REGISTERSCREEN: "RegisterScreen",
  USERINFOSECTION: "UserInfoSection",
  User: "User",
  CHANGELANGUAGE_SCREEN: "ChangeLanguageScreen",
  PRODUCT_DETAIL_SCREEN: "ProductDetailScreen",
  DETAILS: "Detail",
  CHEKCOUT_SCREEN: "CheckoutScreen",
  TODAY_DEAL_SCREEN: "TodayDealScreen",
  HOME: "Home",
  PRODUCT_LIST_FAVORITE_SCREEN: "ProductListFavoriteScreen",
  ABC:"ádádsadsadasdasdád",
};
